#ifndef SMARTFOOTER_GLOBAL_H
#define SMARTFOOTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SMARTFOOTER_LIBRARY)
#define SMARTFOOTER_EXPORT Q_DECL_EXPORT
#else
#define SMARTFOOTER_EXPORT Q_DECL_IMPORT
#endif

#endif // SMARTFOOTER_GLOBAL_H
