#ifndef SMARTMAINSCREEN_GLOBAL_H
#define SMARTMAINSCREEN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SMARTMAINSCREEN_LIBRARY)
#define SMARTMAINSCREEN_EXPORT Q_DECL_EXPORT
#else
#define SMARTMAINSCREEN_EXPORT Q_DECL_IMPORT
#endif

#endif // SMARTMAINSCREEN_GLOBAL_H
