#ifndef MULTICASTSENDER_GLOBAL_H
#define MULTICASTSENDER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MULTICASTSENDER_LIBRARY)
#define MULTICASTSENDER_EXPORT Q_DECL_EXPORT
#else
#define MULTICASTSENDER_EXPORT Q_DECL_IMPORT
#endif

#endif // MULTICASTSENDER_GLOBAL_H
