#ifndef SHAREDDATAMODEL_GLOBAL_H
#define SHAREDDATAMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SHAREDDATAMODEL_LIBRARY)
#define SHAREDDATAMODEL_EXPORT Q_DECL_EXPORT
#else
#define SHAREDDATAMODEL_EXPORT Q_DECL_IMPORT
#endif

#endif // SHAREDDATAMODEL_GLOBAL_H
