#ifndef MULTICASTRECEIVER_GLOBAL_H
#define MULTICASTRECEIVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MULTICASTRECEIVER_LIBRARY)
#define MULTICASTRECEIVER_EXPORT Q_DECL_EXPORT
#else
#define MULTICASTRECEIVER_EXPORT Q_DECL_IMPORT
#endif

#endif // MULTICASTRECEIVER_GLOBAL_H
